PersonnelManagement/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Model;
using Services.Interfaces;

namespace PersonnelManagement.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly ICRUD<Department> _departmentService;

        public DepartmentController(ICRUD<Department> departmentService)
        {
            _departmentService = departmentService ?? throw new ArgumentNullException(nameof(departmentService), "Parameter can't be null");
        }

        [HttpGet]
        public ActionResult All() => View(_departmentService.GetAll());

        [HttpGet]
        public ActionResult Add()
        {
            var departments = _departmentService.GetAll();
            ViewBag.AllDepartments = new SelectList(departments, "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Add(Department department)
        {
            if (department is null)
            {
                return BadRequest();
            }

            await _departmentService.CreateAsync(department);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<ActionResult> Change(int id)
        {
            Department? department = await _departmentService.GetAsync(id);
            if (department is null)
            {
                return BadRequest();
            }
            var departments = _departmentService.GetAll();
            ViewBag.AllDepartments = new SelectList(departments, "Id", "Name", department.GroupDepartmentId);
            return View(department);
        }

        [HttpPost]
        public async Task<ActionResult> Change(Department department)
        {
            if (department is null)
            {
                return BadRequest();
            }

            await _departmentService.UpdateAsync(department);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            await _departmentService.DeleteAsync(id);

            return RedirectToAction(nameof(All));
        }
    }
}

PersonnelManagement/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Model;
using Services.Interfaces;

namespace PersonnelManagement.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly ICRUD<Employee> _employeeService;

        public EmployeeController(ICRUD<Employee> employeeService)
        {
            _employeeService = employeeService ?? throw new ArgumentNullException(nameof(employeeService), "Parameter can't be null");
        }

        [HttpGet]
        public ActionResult All() => View(_employeeService.GetAll());

        [HttpGet]
        public ActionResult Add() => View();

        [HttpPost]
        public async Task<ActionResult> Add(Employee employee)
        {
            if (employee is null)
            {
                return BadRequest();
            }
            await _employeeService.CreateAsync(employee);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<ActionResult> Change(int id) => View(await _employeeService.GetAsync(id));

        [HttpPost]
        public async Task<ActionResult> Change(Employee employee)
        {
            if (employee is null)
            {
                return BadRequest();
            }

            await _employeeService.UpdateAsync(employee);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            await _employeeService.DeleteAsync(id);

            return RedirectToAction(nameof(All));
        }
    }
}

PersonnelManagement/Controllers/PersonnelOperationsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Model;
using Model.Helpers;
using Model.ViewModel;
using Services.Interfaces;

namespace PersonnelManagement.Controllers
{
    public class PersonnelOperationsController : Controller
    {
        private readonly ICRUD<Employee> _employeeService;
        private readonly ICRUD<Department> _departmentService;
        private readonly ICRUD<PersonnelMovements> _personnelMovements;
        private readonly IMapper _mapper;

        public PersonnelOperationsController(ICRUD<Employee> employeeService, ICRUD<Department> departmentService,
            ICRUD<PersonnelMovements> personnelMovements, IMapper mapper)
        {
            _employeeService = employeeService ?? throw new ArgumentNullException(nameof(employeeService), "Parameter can't be null");
            _departmentService = departmentService ?? throw new ArgumentNullException(nameof(departmentService), "Parameter can't be null");
            _personnelMovements = personnelMovements ?? throw new ArgumentNullException(nameof(personnelMovements), "Parameter can't be null");
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper), "Parameter can't be null");
        }

        [HttpGet]
        public IActionResult All() => View();

        [HttpGet]
        public IActionResult Recruitment()
        {
            var departments = _departmentService.GetAll();
            ViewBag.AllDepartments = new SelectList(departments, "Id", "Name");

            var employees = _employeeService.GetAll();
            ViewBag.AllEmployees = new SelectList(employees, "Id", "Presentation");
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Recruitment(Recruitment recruitment)
        {
            if (recruitment is null)
            {
                return BadRequest();
            }

            var recruitingMovement = _mapper.Map<PersonnelMovements>(recruitment);
            await _personnelMovements.CreateAsync(recruitingMovement);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public IActionResult Dismissal()
        {
            var employees = _employeeService.GetAll();
            ViewBag.AllEmployees = new SelectList(employees, "Id", "Presentation");
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Dismissal(Dismissal dismissal)
        {
            if (dismissal is null)
            {
                return BadRequest();
            }


            var dismissalMovement = _personnelMovements.GetAll().Where(p => p.EmployeeId == dismissal.EmployeeId & p.DateStart < dismissal.Date).FirstOrDefault();
            if (dismissalMovement is null)
            {
                return NotFound(); //нет сотрудника работающего
            }

            dismissalMovement.DateEnd = dismissal.Date;
            await _personnelMovements.UpdateAsync(dismissalMovement);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public IActionResult Transfer()
        {
            var departments = _departmentService.GetAll();
            ViewBag.AllDepartments = new SelectList(departments, "Id", "Name");

            var employees = _employeeService.GetAll();
            ViewBag.AllEmployees = new SelectList(employees, "Id", "Presentation");
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Transfer(Transfer transfer)
        {
            if (transfer is null)
            {
                return BadRequest();
            }

            var oldDepartment = _personnelMovements.GetAll().Where(p => p.EmployeeId == transfer.EmployeeId && p.DateStart < transfer.Date & p.DateEnd == DateTime.MinValue).FirstOrDefault();
            if (oldDepartment is null)
            {
                return NotFound(); //нет сотрудника работающего
            }

            oldDepartment.DateEnd = transfer.Date;
            await _personnelMovements.UpdateAsync(oldDepartment);

            var newDepartment = _mapper.Map<PersonnelMovements>(transfer);

            await _personnelMovements.CreateAsync(newDepartment);

            return RedirectToAction(nameof(All));
        }
    }
}

PersonnelManagement/Controllers/ReportController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Model;
using Model.ViewModel.Reports;
using Services.Interfaces;

namespace PersonnelManagement.Controllers
{
    public class ReportController : Controller
    {
        private readonly ICRUD<Department> _departmentService;
        private readonly IReport _reportService;

        public ReportController(ICRUD<Department> departmentService, IReport reportService)
        {
            _departmentService = departmentService ?? throw new ArgumentNullException(nameof(departmentService), "Parameter can't be null");
            _reportService = reportService ?? throw new ArgumentNullException(nameof(reportService), "Parameter can't be null");
        }

        [HttpGet]
        public IActionResult All()
        {
            var departments = _departmentService.GetAll();
            ViewBag.AllDepartments = new SelectList(departments, "Id", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Generate(ParameterReportEmployeesInDepartment parameterReport)
        {
            if (parameterReport is null)
            {
                return BadRequest();
            }

            var departments = _departmentService.GetAll();
            ViewBag.AllDepartments = new SelectList(departments, "Id", "Name");
            return View("ReportEmployeesInDepartment", _reportService.GetReportEmployeesInDepartment(parameterReport));
        }
    }
}

PersonnelManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PersonnelManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PersonnelManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="All">Company structure</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="All">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PersonnelOperations" asp-action="All">Personel operations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="All">Reports</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
       
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>